update gobr

diff --git a/gobr b/gobr
--- a/gobr
+++ b/gobr
@@ -1,14 +1,29 @@
 #!/bin/zsh
 
+# set clean function
+function run_clean() {
+    if [ -e "./$1" ]; then
+        rm $1
+    fi
+}
+
+# set failed function
+function run_failed() {
+    echo -e "\033[41m RUN FAILED \033[0m"
+    run_clean $1
+    exit 1
+}
+
 # get build name and sub args
 bin_name=$1
 shift
 sub_args=$@
 
+# check SIGINT
+trap "run_failed $bin_name" INT
+
 # remove old build
-if [ -e "./$bin_name" ]; then
-    rm $bin_name
-fi
+run_clean $bin_name
 
 # build file
 echo -e "\033[44m START $bin_name \033[0m"
@@ -18,9 +33,8 @@ go build "$bin_name.go"
 if [ -e $bin_name ]; then
     chmod +x $bin_name
     eval "./$bin_name $sub_args"
-    rm $bin_name
+    run_clean $bin_name
     echo -e "\033[42m RUN FINISH \033[0m"
 else
-    echo -e "\033[41m RUN FAILED \033[0m"
-    exit 1
+    fun_failed $bin_name
 fi
